import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
xipfs.c
lwt.c
lwt_signal.c
lwt_shm.c
server.c
""")

group = DefineGroup('Extends', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
